services:
  - type: web
    name: mutual-fund-analyzer-api
    env: python
    buildCommand: |
      cd frontend && npm install && npm run build &&
      pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production 